// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/heartbeat/v1/heartbeat.proto

package heartbeat_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceStatus int32

const (
	ServiceStatus_SERVICE_UP          ServiceStatus = 0
	ServiceStatus_SERVICE_DOWN        ServiceStatus = 1
	ServiceStatus_SERVICE_BUSY        ServiceStatus = 2
	ServiceStatus_SERVICE_UNAVAILABLE ServiceStatus = 3
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_UP",
		1: "SERVICE_DOWN",
		2: "SERVICE_BUSY",
		3: "SERVICE_UNAVAILABLE",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_UP":          0,
		"SERVICE_DOWN":        1,
		"SERVICE_BUSY":        2,
		"SERVICE_UNAVAILABLE": 3,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_heartbeat_v1_heartbeat_proto_enumTypes[0].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_proto_heartbeat_v1_heartbeat_proto_enumTypes[0]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_heartbeat_v1_heartbeat_proto_rawDescGZIP(), []int{0}
}

type HeartbeatServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Up     bool          `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
	Status ServiceStatus `protobuf:"varint,2,opt,name=status,proto3,enum=heartbeat.v1.ServiceStatus" json:"status,omitempty"`
}

func (x *HeartbeatServiceResponse) Reset() {
	*x = HeartbeatServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_heartbeat_v1_heartbeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatServiceResponse) ProtoMessage() {}

func (x *HeartbeatServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heartbeat_v1_heartbeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatServiceResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_heartbeat_v1_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatServiceResponse) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *HeartbeatServiceResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_UP
}

var File_proto_heartbeat_v1_heartbeat_proto protoreflect.FileDescriptor

var file_proto_heartbeat_v1_heartbeat_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e,
	0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5f, 0x0a, 0x18, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x75,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x75, 0x70, 0x12, 0x33, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2a, 0x5c, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x55, 0x50, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x44, 0x4f, 0x57,
	0x4e, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x42,
	0x55, 0x53, 0x59, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x32, 0x68,
	0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x54, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x26,
	0x2e, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x68, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_heartbeat_v1_heartbeat_proto_rawDescOnce sync.Once
	file_proto_heartbeat_v1_heartbeat_proto_rawDescData = file_proto_heartbeat_v1_heartbeat_proto_rawDesc
)

func file_proto_heartbeat_v1_heartbeat_proto_rawDescGZIP() []byte {
	file_proto_heartbeat_v1_heartbeat_proto_rawDescOnce.Do(func() {
		file_proto_heartbeat_v1_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_heartbeat_v1_heartbeat_proto_rawDescData)
	})
	return file_proto_heartbeat_v1_heartbeat_proto_rawDescData
}

var file_proto_heartbeat_v1_heartbeat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_heartbeat_v1_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_heartbeat_v1_heartbeat_proto_goTypes = []interface{}{
	(ServiceStatus)(0),               // 0: heartbeat.v1.ServiceStatus
	(*HeartbeatServiceResponse)(nil), // 1: heartbeat.v1.HeartbeatServiceResponse
	(*emptypb.Empty)(nil),            // 2: google.protobuf.Empty
}
var file_proto_heartbeat_v1_heartbeat_proto_depIdxs = []int32{
	0, // 0: heartbeat.v1.HeartbeatServiceResponse.status:type_name -> heartbeat.v1.ServiceStatus
	2, // 1: heartbeat.v1.HeartbeatService.HeartbeatRequest:input_type -> google.protobuf.Empty
	1, // 2: heartbeat.v1.HeartbeatService.HeartbeatRequest:output_type -> heartbeat.v1.HeartbeatServiceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_heartbeat_v1_heartbeat_proto_init() }
func file_proto_heartbeat_v1_heartbeat_proto_init() {
	if File_proto_heartbeat_v1_heartbeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_heartbeat_v1_heartbeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_heartbeat_v1_heartbeat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_heartbeat_v1_heartbeat_proto_goTypes,
		DependencyIndexes: file_proto_heartbeat_v1_heartbeat_proto_depIdxs,
		EnumInfos:         file_proto_heartbeat_v1_heartbeat_proto_enumTypes,
		MessageInfos:      file_proto_heartbeat_v1_heartbeat_proto_msgTypes,
	}.Build()
	File_proto_heartbeat_v1_heartbeat_proto = out.File
	file_proto_heartbeat_v1_heartbeat_proto_rawDesc = nil
	file_proto_heartbeat_v1_heartbeat_proto_goTypes = nil
	file_proto_heartbeat_v1_heartbeat_proto_depIdxs = nil
}
